In [47]:
import pandas as pd
import yfinance as yf

events = pd.read_csv("../data/processed/tesla_events.csv")
events.head()

  Ticker  event_id  event_date           event_name      event_type
0   TSLA  TSLA_001  25/01/2023     Q4 2022 Earnings        Earnings
1   TSLA  TSLA_002  19/04/2023     Q1 2023 Earnings        Earnings
2   TSLA  TSLA_003  24/01/2024     Q4 2023 Earnings        Earnings
3   TSLA  TSLA_004  23/04/2024     Q1 2024 Earnings        Earnings
4   TSLA  TSLA_005  21/11/2019  Cybertruck Unveiled  Product Launch

In [48]:
import sys

sys.path.append("../reusable_code")

from event_window import get_event_window

In [49]:
events["event_date"] = pd.to_datetime(events["event_date"])

C:\Users\adino\AppData\Local\Temp\ipykernel_6012\2680049731.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  events["event_date"] = pd.to_datetime(events["event_date"])

In [50]:
tesla = yf.download(
    "TSLA",
    start="2019-01-01",
    end="2026-01-01",
    auto_adjust=True
)
tesla.columns = tesla.columns.get_level_values(0)

[*********************100%***********************]  1 of 1 completed

In [51]:
tesla.to_csv("../data/raw/TSLA_stock_2019_2026.csv")

In [52]:
tesla = pd.read_csv(
    "../data/raw/TSLA_stock_2019_2026.csv"
)

In [53]:
tesla.head()

         Date      Close       High        Low       Open     Volume
0  2019-01-02  20.674667  21.008667  19.920000  20.406668  174879000
1  2019-01-03  20.024000  20.626667  19.825333  20.466667  104478000
2  2019-01-04  21.179333  21.200001  20.181999  20.400000  110911500
3  2019-01-07  22.330667  22.449333  21.183332  21.448000  113268000
4  2019-01-08  22.356667  22.934000  21.801332  22.797333  105127500

In [54]:
tesla.info()

<class 'pandas.DataFrame'>
RangeIndex: 1760 entries, 0 to 1759
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1760 non-null   str
 1   Close   1760 non-null   float64
 2   High    1760 non-null   float64
 3   Low     1760 non-null   float64
 4   Open    1760 non-null   float64
 5   Volume  1760 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 82.6 KB

In [55]:
tesla["Date"] = pd.to_datetime(tesla["Date"])
tesla.info()

<class 'pandas.DataFrame'>
RangeIndex: 1760 entries, 0 to 1759
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1760 non-null   datetime64[us]
 1   Close   1760 non-null   float64
 2   High    1760 non-null   float64
 3   Low     1760 non-null   float64
 4   Open    1760 non-null   float64
 5   Volume  1760 non-null   int64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 82.6 KB

In [56]:
tesla.head()

        Date      Close       High        Low       Open     Volume
0 2019-01-02  20.674667  21.008667  19.920000  20.406668  174879000
1 2019-01-03  20.024000  20.626667  19.825333  20.466667  104478000
2 2019-01-04  21.179333  21.200001  20.181999  20.400000  110911500
3 2019-01-07  22.330667  22.449333  21.183332  21.448000  113268000
4 2019-01-08  22.356667  22.934000  21.801332  22.797333  105127500

In [57]:
events.head()

  Ticker  event_id event_date           event_name      event_type
0   TSLA  TSLA_001 2023-01-25     Q4 2022 Earnings        Earnings
1   TSLA  TSLA_002 2023-04-19     Q1 2023 Earnings        Earnings
2   TSLA  TSLA_003 2024-01-24     Q4 2023 Earnings        Earnings
3   TSLA  TSLA_004 2024-04-23     Q1 2024 Earnings        Earnings
4   TSLA  TSLA_005 2019-11-21  Cybertruck Unveiled  Product Launch

In [58]:
get_event_window("TSLA_001",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
1022,TSLA_001,Q4 2022 Earnings,Earnings,0,2023-01-24,143.889999,0.000000
1023,TSLA_001,Q4 2022 Earnings,Earnings,1,2023-01-25,144.429993,0.375282
1024,TSLA_001,Q4 2022 Earnings,Earnings,2,2023-01-26,160.270004,11.383699
1025,TSLA_001,Q4 2022 Earnings,Earnings,3,2023-01-27,177.899994,23.636107
1026,TSLA_001,Q4 2022 Earnings,Earnings,4,2023-01-30,166.660004,15.824591
1027,TSLA_001,Q4 2022 Earnings,Earnings,5,2023-01-31,173.220001,20.383628

In [59]:
get_event_window("TSLA_004",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
1334,TSLA_004,Q1 2024 Earnings,Earnings,0,2024-04-22,142.050003,0.000000
1335,TSLA_004,Q1 2024 Earnings,Earnings,1,2024-04-23,144.679993,1.851453
1336,TSLA_004,Q1 2024 Earnings,Earnings,2,2024-04-24,162.130005,14.135869
1337,TSLA_004,Q1 2024 Earnings,Earnings,3,2024-04-25,170.179993,19.802879
1338,TSLA_004,Q1 2024 Earnings,Earnings,4,2024-04-26,168.289993,18.472362
1339,TSLA_004,Q1 2024 Earnings,Earnings,5,2024-04-29,194.050003,36.606828

In [60]:
get_event_window("TSLA_005",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
224,TSLA_005,Cybertruck Unveiled,Product Launch,0,2019-11-20,23.481333,0.000000
225,TSLA_005,Cybertruck Unveiled,Product Launch,1,2019-11-21,23.655333,0.741013
226,TSLA_005,Cybertruck Unveiled,Product Launch,2,2019-11-22,22.202667,-5.445456
227,TSLA_005,Cybertruck Unveiled,Product Launch,3,2019-11-25,22.422667,-4.508544
228,TSLA_005,Cybertruck Unveiled,Product Launch,4,2019-11-26,21.927999,-6.615184
229,TSLA_005,Cybertruck Unveiled,Product Launch,5,2019-11-27,22.086000,-5.942305

In [61]:
get_event_window("TSLA_006",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
613,TSLA_006,Model S Plaid Delivery Event,Product Launch,0,2021-06-09,199.593338,0.000000
614,TSLA_006,Model S Plaid Delivery Event,Product Launch,1,2021-06-10,203.373337,1.893850
615,TSLA_006,Model S Plaid Delivery Event,Product Launch,2,2021-06-11,203.296661,1.855434
616,TSLA_006,Model S Plaid Delivery Event,Product Launch,3,2021-06-14,205.896667,3.158086
617,TSLA_006,Model S Plaid Delivery Event,Product Launch,4,2021-06-15,199.786667,0.096861
618,TSLA_006,Model S Plaid Delivery Event,Product Launch,5,2021-06-16,201.623337,1.017067

In [62]:
get_event_window("TSLA_007",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
986,TSLA_007,Tesla Semi Delivery Event,Product Launch,0,2022-11-30,194.699997,0.000000
987,TSLA_007,Tesla Semi Delivery Event,Product Launch,1,2022-12-01,194.699997,0.000000
988,TSLA_007,Tesla Semi Delivery Event,Product Launch,2,2022-12-02,194.860001,0.082180
989,TSLA_007,Tesla Semi Delivery Event,Product Launch,3,2022-12-05,182.449997,-6.291731
990,TSLA_007,Tesla Semi Delivery Event,Product Launch,4,2022-12-06,179.820007,-7.642522
991,TSLA_007,Tesla Semi Delivery Event,Product Launch,5,2022-12-07,174.039993,-10.611199

In [63]:
get_event_window("TSLA_009",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
1015,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,0,2023-01-12,123.559998,0.000000
1016,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,1,2023-01-13,122.400002,-0.938812
1017,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,2,2023-01-17,131.490005,6.417941
1018,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,3,2023-01-18,128.779999,4.224669
1019,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,4,2023-01-19,127.169998,2.921658
1020,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,5,2023-01-20,133.419998,7.979929

In [64]:
get_event_window("TSLA_009",events,tesla)

,event_id,event_name,event_type,day,Date,Close,return_from_day_0
1015,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,0,2023-01-12,123.559998,0.000000
1016,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,1,2023-01-13,122.400002,-0.938812
1017,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,2,2023-01-17,131.490005,6.417941
1018,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,3,2023-01-18,128.779999,4.224669
1019,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,4,2023-01-19,127.169998,2.921658
1020,TSLA_009,Global Vehicle Price Cuts,Pricing Strategy,5,2023-01-20,133.419998,7.979929

In [65]:
get_event_window("TSLA_011",events,tesla)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [66]:
from importlib import reload
import event_window

reload(event_window)

from event_window import get_event_window

In [79]:
get_event_window("TSLA_011", events, tesla)

,event_id,event_name,event_type,event_date,day,Date,Close,return_from_day_0
1333,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,0,2024-04-19,147.050003,0.000000
1334,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,1,2024-04-22,142.050003,-3.400204
1335,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,2,2024-04-23,144.679993,-1.611704
1336,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,3,2024-04-24,162.130005,10.255016
1337,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,4,2024-04-25,170.179993,15.729336
1338,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,5,2024-04-26,168.289993,14.444060

In [80]:
get_event_window("TSLA_023", events, tesla)

,event_id,event_name,event_type,event_date,day,Date,Close,return_from_day_0
1245,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,2023-12-13,0,2023-12-12,237.009995,0.000000
1246,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,2023-12-13,1,2023-12-13,239.289993,0.961984
1247,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,2023-12-13,2,2023-12-14,251.050003,5.923804
1248,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,2023-12-13,3,2023-12-15,253.500000,6.957515
1249,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,2023-12-13,4,2023-12-18,252.080002,6.358385
1250,TSLA_023,Autopilot Recall Affecting Over 2 Million Vehi...,Recall,2023-12-13,5,2023-12-19,257.220001,8.527069

In [81]:
import pandas as pd

spy = pd.read_csv("../data/raw/SPY_stock_2019_2026.csv")

spy["Date"] = pd.to_datetime(spy["Date"])

In [82]:
window = get_event_window("TSLA_011", events, tesla)

In [83]:
# Add SPY closing prices for the same trading dates
window = window.merge(
    spy[["Date", "Close"]],
    on="Date",
    how="left",
    suffixes=("", "_SPY")
)

# Rename the SPY closing-price column
window = window.rename(
    columns={"Close_SPY": "SPY_Close"}
)

# Get SPY's Day 0 closing price
spy_day_0_close = window.loc[
    window["day"] == 0,
    "SPY_Close"
].iloc[0]

# Calculate SPY return from the same Day 0 baseline
window["SPY_return_from_day_0"] = (
    (window["SPY_Close"] / spy_day_0_close) - 1
) * 100

# Calculate Tesla's return relative to the market
window["abnormal_return"] = (
    window["return_from_day_0"]
    - window["SPY_return_from_day_0"]
)

window

,event_id,event_name,event_type,event_date,day,Date,Close,return_from_day_0,SPY_Close,SPY_return_from_day_0,abnormal_return
0,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,0,2024-04-19,147.050003,0.000000,482.153473,0.000000,0.000000
1,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,1,2024-04-22,142.050003,-3.400204,486.593719,0.920920,-4.321124
2,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,2,2024-04-23,144.679993,-1.611704,492.367950,2.118512,-3.730215
3,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,3,2024-04-24,162.130005,10.255016,492.134216,2.070035,8.184982
4,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,4,2024-04-25,170.179993,15.729336,490.264648,1.682281,14.047056
5,TSLA_011,Major Price Reductions Across Key Models,Pricing Strategy,2024-04-20,5,2024-04-26,168.289993,14.444060,494.909363,2.645608,11.798452

In [84]:
window = get_event_window("TSLA_007", events, tesla)

In [85]:
window = window.merge(
    spy[["Date", "Close"]],
    on="Date",
    how="left",
    suffixes=("", "_SPY")
)

# Rename the SPY closing-price column
window = window.rename(
    columns={"Close_SPY": "SPY_Close"}
)

# Get SPY's Day 0 closing price
spy_day_0_close = window.loc[
    window["day"] == 0,
    "SPY_Close"
].iloc[0]

# Calculate SPY return from the same Day 0 baseline
window["SPY_return_from_day_0"] = (
    (window["SPY_Close"] / spy_day_0_close) - 1
) * 100

# Calculate Tesla's return relative to the market
window["abnormal_return"] = (
    window["return_from_day_0"]
    - window["SPY_return_from_day_0"]
)

window

,event_id,event_name,event_type,event_date,day,Date,Close,return_from_day_0,SPY_Close,SPY_return_from_day_0,abnormal_return
0,TSLA_007,Tesla Semi Delivery Event,Product Launch,2022-12-01,0,2022-11-30,194.699997,0.000000,388.035187,0.000000,0.000000
1,TSLA_007,Tesla Semi Delivery Event,Product Launch,2022-12-01,1,2022-12-01,194.699997,0.000000,387.749573,-0.073605,0.073605
2,TSLA_007,Tesla Semi Delivery Event,Product Launch,2022-12-01,2,2022-12-02,194.860001,0.082180,387.302338,-0.188862,0.271041
3,TSLA_007,Tesla Semi Delivery Event,Product Launch,2022-12-01,3,2022-12-05,182.449997,-6.291731,380.335052,-1.984391,-4.307340
4,TSLA_007,Tesla Semi Delivery Event,Product Launch,2022-12-01,4,2022-12-06,179.820007,-7.642522,374.852631,-3.397258,-4.245264
5,TSLA_007,Tesla Semi Delivery Event,Product Launch,2022-12-01,5,2022-12-07,174.039993,-10.611199,374.214905,-3.561605,-7.049593