In [1]:
import sys
import os
import pandas as pd

sys.path.append(os.path.abspath(".."))

In [2]:
from reusable_code.get_reddit_window import get_reddit_window
from reusable_code.collect_event_reddit import collect_event_reddit

In [3]:
events_with_queries = pd.read_csv(
    "../data/processed/events/tesla_events_with_queries.csv"
)

In [4]:
event_dataset = pd.read_csv(
    "../data/processed/tesla_event_dataset.csv"
)

In [5]:
test_event = events_with_queries.iloc[0]

In [6]:
print("Event ID:", test_event["event_id"])
print("Event:", test_event["event_name"])
print("Event date:", test_event["event_date"])
print("Search query:", test_event["search_query"])

Event ID: TSLA_001
Event: Q4 2022 Earnings
Event date: 2023-01-25
Search query: Tesla earnings

In [7]:
start_date, end_date = get_reddit_window(
    test_event["event_id"],
    test_event["event_date"],
    event_dataset
)

In [8]:
print("Reddit start:", start_date)
print("Reddit end:", end_date)

Reddit start: 2023-01-25 00:00:00
Reddit end: 2023-01-26 00:00:00

In [12]:
import importlib
import reusable_code.collect_event_reddit as reddit_module

importlib.reload(reddit_module)

collect_event_reddit = reddit_module.collect_event_reddit

In [13]:
reddit_posts = collect_event_reddit(
    test_event["event_id"],
    test_event["search_query"],
    start_date,
    end_date
)

In [14]:
print("Number of posts:", len(reddit_posts))
reddit_posts.head()

Number of posts: 18

,event_id,post_id,subreddit,created_date,title,selftext,score,num_comments,url,search_query
0,TSLA_001,10la433,teslainvestorsclub,2023-01-25 21:22:08,Tesla 2022 Q4 Earnings report,[deleted],0,0,,Tesla earnings
1,TSLA_001,10lo61w,teslainvestorsclub,2023-01-26 09:40:18,[OC] Tesla's income statement for the year 202...,,61,5,https://i.redd.it/85ds40e9ycea1.png,Tesla earnings
2,TSLA_001,10ltyc0,teslainvestorsclub,2023-01-26 15:09:09,"Tesla Stock Surges On Earnings, Upcoming Vehic...",,66,41,https://www.investors.com/news/tesla-stock-ami...,Tesla earnings
3,TSLA_001,10m376s,teslainvestorsclub,2023-01-26 21:34:34,Opinion: Tesla beat earnings thanks to $300 mi...,,0,12,https://www.marketwatch.com/story/tesla-beat-e...,Tesla earnings
4,TSLA_001,10l9spv,stocks,2023-01-25 21:09:32,Tesla earnings are out — here are the numbers,Electric vehicle maker Tesla reported earnings...,495,574,https://www.reddit.com/r/stocks/comments/10l9s...,Tesla earnings

In [15]:
reddit_posts

,event_id,post_id,subreddit,created_date,title,selftext,score,num_comments,url,search_query
0,TSLA_001,10la433,teslainvestorsclub,2023-01-25 21:22:08,Tesla 2022 Q4 Earnings report,[deleted],0,0,,Tesla earnings
1,TSLA_001,10lo61w,teslainvestorsclub,2023-01-26 09:40:18,[OC] Tesla's income statement for the year 202...,,61,5,https://i.redd.it/85ds40e9ycea1.png,Tesla earnings
2,TSLA_001,10ltyc0,teslainvestorsclub,2023-01-26 15:09:09,"Tesla Stock Surges On Earnings, Upcoming Vehic...",,66,41,https://www.investors.com/news/tesla-stock-ami...,Tesla earnings
3,TSLA_001,10m376s,teslainvestorsclub,2023-01-26 21:34:34,Opinion: Tesla beat earnings thanks to $300 mi...,,0,12,https://www.marketwatch.com/story/tesla-beat-e...,Tesla earnings
4,TSLA_001,10l9spv,stocks,2023-01-25 21:09:32,Tesla earnings are out — here are the numbers,Electric vehicle maker Tesla reported earnings...,495,574,https://www.reddit.com/r/stocks/comments/10l9s...,Tesla earnings
5,TSLA_001,10l9stf,stocks,2023-01-25 21:09:38,Tesla earnings,[removed],8,3,,Tesla earnings
6,TSLA_001,10la1qj,stocks,2023-01-25 21:19:34,Tesla Price After Earnings,[removed],1,0,https://www.reddit.com/r/stocks/comments/10la1...,Tesla earnings
7,TSLA_001,10lakui,stocks,2023-01-25 21:41:10,"Stock Market News of the Day: Tesla, Boeing, I...",[removed],1,0,,Tesla earnings
8,TSLA_001,10klvnt,wallstreetbets,2023-01-25 01:04:08,Positive of negative Tesla earnings tomorrow? ...,,1,1,https://www.cnbc.com/video/2023/01/23/why-tesl...,Tesla earnings
9,TSLA_001,10kxctf,wallstreetbets,2023-01-25 12:19:33,Tesla Earnings Estimate,"Based on the production and deliveries, the es...",0,3,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
10,TSLA_001,10l1ejw,wallstreetbets,2023-01-25 15:34:38,What are everybody’s thoughts on Tesla earning...,I’ve seen some bullish news about them droppin...,2,56,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
11,TSLA_001,10l3fhe,wallstreetbets,2023-01-25 16:57:54,Calls or puts for Tesla earnings?,[removed],1,1,,Tesla earnings
12,TSLA_001,10l9tf8,wallstreetbets,2023-01-25 21:10:18,Tesla earnings,,9,2,https://twitter.com/investingcom/status/161835...,Tesla earnings
13,TSLA_001,10laicu,wallstreetbets,2023-01-25 21:38:17,"Stock Market News of the Day: Tesla, Boeing, I...",**Major** **Earnings:**\n\n**- Boeing** report...,9,6,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
14,TSLA_001,10lddyo,wallstreetbets,2023-01-25 23:37:38,Tesla Earnings Call Notes,earnings call key notes \n\----------------...,18,19,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
15,TSLA_001,10lfzjd,wallstreetbets,2023-01-26 01:36:31,Called tesla x2 earlier before earnings. Wish ...,[removed],3,15,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
16,TSLA_001,10lrbqm,wallstreetbets,2023-01-26 13:04:05,Tesla earnings call highlights!,,15,15,https://www.reddit.com/gallery/10lrbqm,Tesla earnings
17,TSLA_001,10lepaf,teslamotors,2023-01-26 00:35:42,Tesla Q4 Earnings Results,,1,0,https://i.redd.it/1pvltgz2rbea1.jpg,Tesla earnings

In [16]:
from reusable_code.clean_reddit_posts import clean_reddit_posts

In [17]:
reddit_posts_clean = clean_reddit_posts(reddit_posts)

In [18]:
reddit_posts_clean[
    ["title", "selftext", "text"]
].head(10)

,title,selftext,text
0,Tesla 2022 Q4 Earnings report,,Tesla 2022 Q4 Earnings report
1,[OC] Tesla's income statement for the year 202...,,[OC] Tesla's income statement for the year 202...
2,"Tesla Stock Surges On Earnings, Upcoming Vehic...",,"Tesla Stock Surges On Earnings, Upcoming Vehic..."
3,Opinion: Tesla beat earnings thanks to $300 mi...,,Opinion: Tesla beat earnings thanks to $300 mi...
4,Tesla earnings are out — here are the numbers,Electric vehicle maker Tesla reported earnings...,Tesla earnings are out — here are the numbers ...
5,Tesla earnings,,Tesla earnings
6,Tesla Price After Earnings,,Tesla Price After Earnings
7,"Stock Market News of the Day: Tesla, Boeing, I...",,"Stock Market News of the Day: Tesla, Boeing, I..."
8,Positive of negative Tesla earnings tomorrow? ...,,Positive of negative Tesla earnings tomorrow? ...
9,Tesla Earnings Estimate,"Based on the production and deliveries, the es...",Tesla Earnings Estimate Based on the productio...

In [20]:
reddit_posts_clean.columns

Index(['event_id', 'post_id', 'subreddit', 'created_date', 'title', 'selftext',
       'score', 'num_comments', 'url', 'search_query', 'text'],
      dtype='str')

In [21]:
(reddit_posts_clean["text"] == "").sum()

np.int64(0)

In [22]:
from reusable_code.build_reddit_dataset import build_reddit_dataset

In [23]:
events_with_queries = pd.read_csv(
    "../data/processed/events/tesla_events_with_queries.csv"
)

event_dataset = pd.read_csv(
    "../data/processed/tesla_event_dataset.csv"
)

In [25]:
import importlib
import reusable_code.collect_event_reddit as reddit_module

importlib.reload(reddit_module)

collect_event_reddit = reddit_module.collect_event_reddit

In [32]:
import importlib
import reusable_code.collect_event_reddit as reddit_module
import reusable_code.build_reddit_dataset as dataset_module

importlib.reload(reddit_module)
importlib.reload(dataset_module)

collect_event_reddit = reddit_module.collect_event_reddit
build_reddit_dataset = dataset_module.build_reddit_dataset

In [ ]:
import time

In [34]:
response = requests.get(
    url,
    params=params,
    timeout=30
)

time.sleep(1)

NameError: name 'url' is not defined

In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
from reusable_code.collect_event_reddit import collect_event_reddit
from reusable_code.build_reddit_dataset import build_reddit_dataset

In [3]:
import reusable_code.collect_event_reddit as reddit_module

print(reddit_module.__file__)

c:\Users\adino\Documents\Projects\market-impact-analysis\reusable_code\collect_event_reddit.py

In [4]:
import inspect

print(inspect.getsource(collect_event_reddit))

def collect_event_reddit(event_id, search_query, start_date, end_date):

    url = "https://arctic-shift.photon-reddit.com/api/posts/search"

    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)

    subreddits = [
        "teslainvestorsclub",
        "stocks",
        "investing",
        "wallstreetbets",
        "teslamotors"
    ]

    all_posts = []

    for subreddit in subreddits:

        params = {
            "subreddit": subreddit,
            "title": search_query,
            "after": start_date.strftime("%Y-%m-%d"),
            "before": (end_date + pd.Timedelta(days=1)).strftime("%Y-%m-%d"),
            "sort": "asc",
            "limit": 100
        }

        response = requests.get(
            url,
            params=params,
            timeout=30
        )

        if response.status_code != 200:
            print(
                f"Skipped {subreddit} for {event_id}: "
                f"status {response.status_code}"
            )
            continue

        data = response.json()

        all_posts.extend(data["data"])

    posts = pd.DataFrame(all_posts)

    if posts.empty:
        return posts

    posts["event_id"] = event_id
    posts["search_query"] = search_query

    posts["created_date"] = pd.to_datetime(
        posts["created_utc"],
        unit="s"
    )

    columns = [
        "event_id",
        "id",
        "subreddit",
        "created_date",
        "title",
        "selftext",
        "score",
        "num_comments",
        "url",
        "search_query"
    ]

    posts = posts[columns]

    posts = posts.rename(
        columns={"id": "post_id"}
    )

    return posts

In [5]:
reddit_posts = collect_event_reddit(
    test_event["event_id"],
    test_event["search_query"],
    start_date,
    end_date
)

NameError: name 'test_event' is not defined

In [6]:
import pandas as pd

events_with_queries = pd.read_csv(
    "../data/processed/events/tesla_events_with_queries.csv"
)

In [7]:
test_event = events_with_queries.iloc[0]

In [8]:
event_dataset = pd.read_csv(
    "../data/processed/tesla_event_dataset.csv"
)

In [9]:
from reusable_code.get_reddit_window import get_reddit_window

start_date, end_date = get_reddit_window(
    test_event["event_id"],
    test_event["event_date"],
    event_dataset
)

In [12]:
reddit_posts = collect_event_reddit(
    test_event["event_id"],
    test_event["search_query"],
    start_date,
    end_date
)

Skipped teslainvestorsclub for TSLA_001: status 422
Skipped stocks for TSLA_001: status 422

In [13]:
print("Number of posts:", len(reddit_posts))
reddit_posts.head()

Number of posts: 10

,event_id,post_id,subreddit,created_date,title,selftext,score,num_comments,url,search_query
0,TSLA_001,10klvnt,wallstreetbets,2023-01-25 01:04:08,Positive of negative Tesla earnings tomorrow? ...,,1,1,https://www.cnbc.com/video/2023/01/23/why-tesl...,Tesla earnings
1,TSLA_001,10kxctf,wallstreetbets,2023-01-25 12:19:33,Tesla Earnings Estimate,"Based on the production and deliveries, the es...",0,3,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
2,TSLA_001,10l1ejw,wallstreetbets,2023-01-25 15:34:38,What are everybody’s thoughts on Tesla earning...,I’ve seen some bullish news about them droppin...,2,56,https://www.reddit.com/r/wallstreetbets/commen...,Tesla earnings
3,TSLA_001,10l3fhe,wallstreetbets,2023-01-25 16:57:54,Calls or puts for Tesla earnings?,[removed],1,1,,Tesla earnings
4,TSLA_001,10l9tf8,wallstreetbets,2023-01-25 21:10:18,Tesla earnings,,9,2,https://twitter.com/investingcom/status/161835...,Tesla earnings

In [23]:
import importlib
import reusable_code.collect_event_reddit as reddit_module

importlib.reload(reddit_module)

collect_event_reddit = reddit_module.collect_event_reddit

In [24]:
reddit_posts = collect_event_reddit(
    test_event["event_id"],
    test_event["search_query"],
    start_date,
    end_date
)

In [25]:
print("Number of posts:", len(reddit_posts))

reddit_posts[
    ["subreddit", "created_date", "title"]
].head(20)

Number of posts: 28

,subreddit,created_date,title
11,teslainvestorsclub,2023-01-25 21:22:08,Tesla 2022 Q4 Earnings report
22,teslainvestorsclub,2023-01-26 09:40:18,[OC] Tesla's income statement for the year 202...
27,teslainvestorsclub,2023-01-26 15:09:09,"Tesla Stock Surges On Earnings, Upcoming Vehic..."
41,teslainvestorsclub,2023-01-26 21:34:34,Opinion: Tesla beat earnings thanks to $300 mi...
45,stocks,2023-01-25 01:49:59,Tesla plans to spend $3.6 billion more on batt...
76,stocks,2023-01-25 13:16:11,(1/25) Wednesday's Pre-Market Stock Movers & News
118,stocks,2023-01-25 21:09:32,Tesla earnings are out — here are the numbers
119,stocks,2023-01-25 21:09:38,Tesla earnings
124,stocks,2023-01-25 21:19:34,Tesla Price After Earnings
127,stocks,2023-01-25 21:41:10,"Stock Market News of the Day: Tesla, Boeing, I..."
175,stocks,2023-01-26 13:43:02,(1/26) Thursday's Pre-Market Stock Movers & News
219,stocks,2023-01-26 21:18:59,Ideal automotive ratio
427,wallstreetbets,2023-01-25 01:04:08,Positive of negative Tesla earnings tomorrow? ...
590,wallstreetbets,2023-01-25 12:19:33,Tesla Earnings Estimate
600,wallstreetbets,2023-01-25 12:46:06,$TSLA Earnings Thread 1/25/2023
695,wallstreetbets,2023-01-25 15:34:38,What are everybody’s thoughts on Tesla earning...
740,wallstreetbets,2023-01-25 16:57:54,Calls or puts for Tesla earnings?
892,wallstreetbets,2023-01-25 21:10:18,Tesla earnings
913,wallstreetbets,2023-01-25 21:38:17,"Stock Market News of the Day: Tesla, Boeing, I..."
949,wallstreetbets,2023-01-25 23:04:06,Bulls remain in control… the road to 410 conti...

**Running for all 23 events**

In [29]:
import importlib
import reusable_code.collect_event_reddit as reddit_module
import reusable_code.build_reddit_dataset as dataset_module

importlib.reload(reddit_module)
importlib.reload(dataset_module)

collect_event_reddit = reddit_module.collect_event_reddit
build_reddit_dataset = dataset_module.build_reddit_dataset

In [32]:
import importlib
import reusable_code.collect_event_reddit as reddit_module
import reusable_code.build_reddit_dataset as dataset_module

importlib.reload(reddit_module)
importlib.reload(dataset_module)

collect_event_reddit = reddit_module.collect_event_reddit
build_reddit_dataset = dataset_module.build_reddit_dataset

In [33]:
tesla_reddit_posts = build_reddit_dataset(
    events_with_queries,
    event_dataset
)

Collecting Reddit posts for TSLA_001
Saved 28 posts for TSLA_001
Collecting Reddit posts for TSLA_002
Saved 18 posts for TSLA_002
Collecting Reddit posts for TSLA_003
Saved 26 posts for TSLA_003
Collecting Reddit posts for TSLA_004
Saved 45 posts for TSLA_004
Collecting Reddit posts for TSLA_005
Saved 159 posts for TSLA_005
Collecting Reddit posts for TSLA_006
Skipped wallstreetbets for TSLA_006: status 422
Saved 25 posts for TSLA_006
Collecting Reddit posts for TSLA_007
Saved 34 posts for TSLA_007
Collecting Reddit posts for TSLA_008
Saved 45 posts for TSLA_008
Collecting Reddit posts for TSLA_009
Skipped wallstreetbets for TSLA_009: status 422
Saved 75 posts for TSLA_009
Collecting Reddit posts for TSLA_010
Saved 14 posts for TSLA_010
Collecting Reddit posts for TSLA_011
Saved 44 posts for TSLA_011
Collecting Reddit posts for TSLA_012
Saved 102 posts for TSLA_012
Collecting Reddit posts for TSLA_013
Saved 51 posts for TSLA_013
Collecting Reddit posts for TSLA_014
Saved 35 posts for TSLA_014
Collecting Reddit posts for TSLA_015
Saved 2 posts for TSLA_015
Collecting Reddit posts for TSLA_016
No posts found for TSLA_016
Collecting Reddit posts for TSLA_017
Saved 4 posts for TSLA_017
Collecting Reddit posts for TSLA_018
Saved 7 posts for TSLA_018
Collecting Reddit posts for TSLA_019
Saved 13 posts for TSLA_019
Collecting Reddit posts for TSLA_020
Saved 3 posts for TSLA_020
Collecting Reddit posts for TSLA_021
Skipped wallstreetbets for TSLA_021: status 422
Saved 11 posts for TSLA_021
Collecting Reddit posts for TSLA_022
Skipped wallstreetbets for TSLA_022: status 422
Saved 11 posts for TSLA_022
Collecting Reddit posts for TSLA_023
Saved 25 posts for TSLA_023

In [34]:
tesla_reddit_posts.to_csv(
    "../data/processed/reddit/tesla_reddit_posts.csv",
    index=False
)